name: Publish to NPM
on:
  push:
    tags:
      - '*alpha*'
jobs:
  build:
    if: github.event.base_ref == 'ref/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public --tag alpha
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}